// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ZhKg5tdurcLqtedmKQqCZOE5X-gnB-0',
    appId: '1:606807280271:android:2f9c0d03123b66158a7efa',
    messagingSenderId: '606807280271',
    projectId: 'vecindario-app-a746b',
    storageBucket: 'vecindario-app-a746b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtE-jNnVIe4KUWDYD0RbrxrGyn1mQNpWw',
    appId: '1:606807280271:ios:238dd146f2f8328b8a7efa',
    messagingSenderId: '606807280271',
    projectId: 'vecindario-app-a746b',
    storageBucket: 'vecindario-app-a746b.firebasestorage.app',
    iosClientId:
        '606807280271-0dp7grhhsqshms6klu3a9l74h1kbptuh.apps.googleusercontent.com',
    iosBundleId: 'com.vecindario.vecindarioApp',
  );
}
